DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS products CASCADE;
-- DROP TABLE IF EXISTS product_colors CASCADE;
DROP TABLE IF EXISTS product_pictures CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(50) NOT NULL,
  email VARCHAR(50) NOT NULL,
  password VARCHAR(20) NOT NULL
);

CREATE TABLE orders (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
  order_date DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE products (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(50) NOT NULL,
  description VARCHAR(500) NOT NULL,
  price_cents INTEGER NOT NULL,
  material VARCHAR(255) NOT NULL,
  size VARCHAR(50) NOT NULL,
  category VARCHAR(50) NOT NULL,
  color VARCHAR(50) NOT NULL,
  added_date DATE NOT NULL DEFAULT CURRENT_DATE
);

CREATE TABLE order_items (
  order_id INTEGER REFERENCES orders (id) ON DELETE CASCADE,
  product_id INTEGER REFERENCES products (id) ON DELETE CASCADE
);

-- CREATE TABLE product_colors {
--   id SERIAL PRIMARY KEY NOT NULL,
--   product_id INTEGER REFERENCES products (id) ON DELETE CASCADE,
--   color VARCHAR(50) NOT NULL;
-- };

CREATE TABLE product_pictures (
  id SERIAL PRIMARY KEY NOT NULL,
  product_id INTEGER REFERENCES products (id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  is_thumbnail BOOLEAN NOT NULL DEFAULT false
);